### ISSUE TITLE
"Duplicate"?

### ISSUE THREAD

**Issue by frassefraze** [ElVit/esphome_panasonic_heatpump#1]
I don't mean to assume, but it seems like you might be working on something that already has a similar solution out there. It might be beneficial to use your knowledge to enhance what already exists.

https://github.com/DomiStyle/esphome-panasonic-ac

**Comment by ElVit** [comment]
Hi @frassefraze,
no this not a duplicate. 
This repo is based on [HeishaMon](https://github.com/Egyras/HeishaMon).
I only try to create an ESPHome component of it to make it more customizable.
Heishamon is working only for Panasonic Heatpumps.
The link you posted is for Panasonic Airconditioning.

If you look the code more in detail you will see that the heatpump query message is quite larger (203 bytes) than the query message the message from the ac (34 bytes).
Also my approach is to create a man-in-the-middle component, that means I can still use the original Panasonic-Wifi-Module.
The ESP module is currently only listening for the communication between the Heatpump and the Wifi-Module.
I will put some more info in the *.md file to explain how this is working.

But you are right there are many similarities regarding the hardware setup and also the structure of the message.
So thank you for the link. I think the panasonic-ac project will help me to create a real esphome component.

**Comment by frassefraze** [comment]
Oh, I apologize for missing that detail. It's a bit beyond my understanding 😊. Lets hope you find something useful from the link shared, or least get some inspiration to keep up the good work.
